language: android

env:
  global:
  - CI_NAME=travis-ci
  # coveralls repo token
  - secure: Q4dXi7tRbW3ilrZD0uxVTJLoFx4azlGWvdk5GsVkEfFxfMpb0PCV03KgrzReBhCaYC+uN8bkF80aGv0KlVcbrZtmRAVCGDcK8fbP6q8t9l1/YWTeO6i/Pgbri8h7ozrtUtlCv+5c2liBdjwNM6XVI597+VOl1GzAw/5UWqrDCAOin0Ev/JccVLU6/4hJfDGN1Ek/S2UpqozbUNHBYUHHDKqLMud4QhnklIMUHubOT/hBAcS5qZaARoBo7tc0goBry+1LAUrsPSv5mebyq7c2blr3VlrlVxNdfQearDQ6RZBiyABnD9eCCWRMb2XTk7lGXISKkfH9rPys/Wu/DIVHgP/u1qCcv5woDVPK4mXLxY7yafW98EawJxMSppxdNOqq7+MMHE9FNyW0qVtyjlMFPAEvHUBG13Lp4QOntEZWtvVsR/XMRPTn4DRp535ahGcoiyosefqplI7xamNzFdFUHcIBPnbIHyKiFizQtRKDZ0B258K16Wc3IMQTmNPozx4xlxLYvK95rAfF504j9+1+eCvl+Hq1RFGQ+Bgs4a6iMyr1ss9eRMM4SfC6AsvhlZr1FxdNb30ubpmhZz+djOeq4AAgFbLWiLhV6dWS4iEHZv9Y1ep9DSA09+fwVLFTfA5ZHR0uVgYz4k0MKOH5ZrtusH2bBvxUBT6yziko/F5dWpM=
  # bintray user
  - secure: bj8v/vhPHbUvvamWEvm68XNJhkGVrkY2ycPkU2M6nvdfV493XrHq72BNt0SlyY+8jw+uPdBb8w/X6GXgZs+UtlWKqw04fpGypkPPla6iiXDEHQ/IKFqZ2o2bTZ15G0+nxs7IYtUY8uFws8HqX0XNxSgfh/3YPV7WGpdGM0og01s9sQuYIgDZCcUWAsNVBd2dwLL41zNCyPDUpMQ+L1rPdZilhrUeaD5j//YtVS3xYD1CJ4px1F3sfimHFWIzKdKDgIc+fN2inUwTG7rv2ujBMdpU1xKkQq7fDYs2/lL6FYna9BXtDdPeZ1q0jfnU7fOxj9T/lZzSKJR1USKL2cg8JKVsJ8t0SIvIxlLhPXgot9IEebz01/A+E3z1wcxQRFz57uwX/j21P+f8X/ck1F7kd6Ebnk85vvSp214Wx3ComhfUj4b4KleZFgL+yuA6akak1gKR8z1/Ml86JX4X8l4JRN8/ImHYCtqEKYg2HrSyeQ6BdvMXcLCkvOHdNdHwzqHEoB+snTXnV4ifU0ObUolgScQncCGZSBhPj5kXopPtjKUibIkpaVD4KlJPnmI9cAO5BM9l+BJxAelYDPZBceJuebGhlnvLZ01rItLL74gdVc8R1uV6wqa2IiWOTQeVod91ErZGt1MedpZDrqYSSO2TEOPliCUVDnz85hnYaEWnPiY=
  # bintray api key
  - secure: kcoq+HEa7XQ1Qkxj2y03XHyYB6nHtQVUdyvHqIbipO5PHjZTKHKDxw4eIo/OTGZrcvuPD+eTL3QDOr7fVvfYbwfItEe6LTxbaWQmQdHyyw+S4tIC61pLQD4tqTjQCWd7Jk3rodl9nrdvgInz7sWMGvVGAOsJRMqJizPwFGqLyPabiVPXHFqLyW4UhHx7LSUq5Aag7wB3Q/+ijhTJ5Lc65NIJ61ae1WxE8LtubXns5LaYgGKUnUxaiPoRfor4V3v6Fj6TwPqlLdJ/AQL7VWtOVRqzdUwFki/FX9oip44LTs/tLe6aVmITr+SU3QDV7/+FgbvLmEJZK9ipIOXXIbAwNfQzGd6+9LCRl3KPj7kU1PaUQwmEG/QdpX8u3gavAQtfpTfnCV7wkkiYdOWaY+NwB0fMwsdahUp9Z58euatbHg763vXnKCfIk1EL/EzGpW4tPWB6DNvd1uEEOBnmc1GBixtAVxFsOu0R/oEgZSymPlovLzy7jtJNAq9347R4iyzS2WVu1tYKgHiKr8yWCszEF7w5zdup5ZuKG+6sQfELS11U+TG1yv2tlMeF98sSuqmaFKaIv6s+KuweuixqMrkGh1l3o6gmolWtHEPmejCY+pZuEBJd/02fjQyd2Tv+8ok8Umad7k9zbNfoB7j2p5m7Nj8Vx0nzsgf+z9KT+TP54ec=
  # bintray gpg key
  - secure: VbdzebSSUbc49vCHRrEgDYU8GIY2YlCQx4Anf28plUEk9ROhaN/RgvVkS03p54Hz2tLdWQjzcIgtRx5qMrAZWIZ6ASwTJYmWwpNmt8SaZaQ6AMsKidNSyg3r15XRjOekQrfusSQZnZV+6JHeWcqDwRneAG9LgsL6hvbIBpnCU5O4H9k7lswdJtZMQ7V74xz4IaJbVfN+rQ73e4295h9MugzDK6MIyPao6LXW29hYHxaPAzPFQoDfdF4O+vc2MoqVqpc0paq6WNzDGVo8isFW+qngFp7hm9m/i+Upwn3iM8PnbRxCDW2ovoI9d5f0JHEfKhaiuk/K9JzAiMrpAxRculIwdw/7QsXA6tchwflXguUaIXa9aoYGYdDxpY6fGeTqePyjQP9vbK4/fBb2EM3Qh7dXuElpxq95VNxAYpCOEJ2I4PhC5Za4lcqcRSLJ5l9fe3NPYB+v+Lg98LKtUDmtmUort6vMedsYpoeiI1rdMfAEcpAiRhbnGdQdTW2dPlxtQlMnLxqAR1+u52m5tYj7kvJKRO5e9TvKKP7XdMP3Wqi1gvM14nInrvwyIEIJAx0yzRiA6yh6StQtIZ1ATof2vg0vLBEfFGENMXI5dDGPWK+lP0CBZrnU6Fxo1BXXgslm7K2puHeaDuVKdvEm8BPViuC+gkZp/GXgI1il6An7dpM=

install:
- test -z "$BUILD_DOCS" || pip install --user sphinx

script:
- test -z "$BUILD_DOCS" || cd docs
- test -z "$BUILD_DOCS" || make html
- test -z "$BUILD_DOCS" || cd ..

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    # - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    # - addon-google_apis-google-23

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17

after_success:
  - ./gradlew :sdk:cobertura :sdk:coveralls
  - test -z "$BUILD_DOCS" || CURRENT_HASH=`git rev-parse HEAD`
  - test -z "$BUILD_DOCS" || RELEASE_VERSION=`git tag | xargs -I@ git log --format=format:"%ai @%n" -1 @ | sort | awk '{print $4}' | tail -n 1`
  - test -z "$BUILD_DOCS" || RELEASE_HASH=`git rev-list $RELEASE_VERSION -n 1`
  - test -z "$BUILD_DOCS" || if [ "$CURRENT_HASH" = "$RELEASE_HASH" ]; then DEPLOY_DOCS=true; fi
  - test -z "$BUILD_DOCS" || echo $RELEASE_VERSION
  - test -z "$BUILD_DOCS" || echo $CURRENT_HASH
  - test -z "$BUILD_DOCS" || echo $RELEASE_HASH
  - test -z "$BUILD_DOCS" || echo $DEPLOY_DOCS
  - test -z "$DEPLOY_DOCS" || git config --global user.email "evangelists@stormpath.com"
  - test -z "$DEPLOY_DOCS" || git config --global user.name "stormpath-sdk-android Auto Doc Build"
  - test -z "$DEPLOY_DOCS" || git clone git@github.com:stormpath/stormpath.github.io.git
  - test -z "$DEPLOY_DOCS" || cd stormpath.github.io
  - test -z "$DEPLOY_DOCS" || git fetch origin source:source
  - test -z "$DEPLOY_DOCS" || git checkout source
  - test -z "$DEPLOY_DOCS" || rm -rf source/android/latest
  - test -z "$DEPLOY_DOCS" || mkdir -p source/android/latest
  - test -z "$DEPLOY_DOCS" || cp -r ../docs/_build/html source/android/latest
  - test -z "$DEPLOY_DOCS" || cp -r ../docs/_build/html source/android/$RELEASE_VERSION
  - test -z "$DEPLOY_DOCS" || git add --all
  - test -z "$DEPLOY_DOCS" || git commit -m "stormpath-sdk-android release $RELEASE_VERSION"
  - test -z "$DEPLOY_DOCS" || ls -la source/android
  - test -z "$DEPLOY_DOCS" || git push origin source
  - test -z "$DEPLOY_DOCS" || gem install bundler
  - test -z "$DEPLOY_DOCS" || bundle install
  - test -z "$DEPLOY_DOCS" || rake setup_github_pages[git@github.com:stormpath/stormpath.github.io.git]
  - test -z "$DEPLOY_DOCS" || cd _deploy
  - test -z "$DEPLOY_DOCS" || git pull --no-edit -s recursive -X theirs https://github.com/stormpath/stormpath.github.io.git
  - test -z "$DEPLOY_DOCS" || cd ..
  - test -z "$DEPLOY_DOCS" || rake generate
  - test -z "$DEPLOY_DOCS" || cd _deploy
  - test -z "$DEPLOY_DOCS" || git pull --no-edit -s recursive -X theirs https://github.com/stormpath/stormpath.github.io.git
  - test -z "$DEPLOY_DOCS" || cd ..
  - test -z "$DEPLOY_DOCS" || rake deploy
  - test -z "$DEPLOY_DOCS" || cd ..

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - openssl aes-256-cbc -K $encrypted_568555ef9f79_key -iv $encrypted_568555ef9f79_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

deploy:
  provider: script
  script: sh $TRAVIS_BUILD_DIR/deploy.sh
  skip_cleanup: true
  on:
    tags: true