language: android

env:
  global:
  - CI_NAME=travis-ci
  # coveralls repo token
  - secure: Q4dXi7tRbW3ilrZD0uxVTJLoFx4azlGWvdk5GsVkEfFxfMpb0PCV03KgrzReBhCaYC+uN8bkF80aGv0KlVcbrZtmRAVCGDcK8fbP6q8t9l1/YWTeO6i/Pgbri8h7ozrtUtlCv+5c2liBdjwNM6XVI597+VOl1GzAw/5UWqrDCAOin0Ev/JccVLU6/4hJfDGN1Ek/S2UpqozbUNHBYUHHDKqLMud4QhnklIMUHubOT/hBAcS5qZaARoBo7tc0goBry+1LAUrsPSv5mebyq7c2blr3VlrlVxNdfQearDQ6RZBiyABnD9eCCWRMb2XTk7lGXISKkfH9rPys/Wu/DIVHgP/u1qCcv5woDVPK4mXLxY7yafW98EawJxMSppxdNOqq7+MMHE9FNyW0qVtyjlMFPAEvHUBG13Lp4QOntEZWtvVsR/XMRPTn4DRp535ahGcoiyosefqplI7xamNzFdFUHcIBPnbIHyKiFizQtRKDZ0B258K16Wc3IMQTmNPozx4xlxLYvK95rAfF504j9+1+eCvl+Hq1RFGQ+Bgs4a6iMyr1ss9eRMM4SfC6AsvhlZr1FxdNb30ubpmhZz+djOeq4AAgFbLWiLhV6dWS4iEHZv9Y1ep9DSA09+fwVLFTfA5ZHR0uVgYz4k0MKOH5ZrtusH2bBvxUBT6yziko/F5dWpM=
  # bintray user
  - secure: fBFVKB/dZZnG1JN35LYd8xZaC9a20Ucl7TZzf2s9Pq1h1p5pEY9OJnQgSRNhvstxQxN/3/bBJCGUHaaKszeqZ8fo271tAG0kzmjgl92bsrUr63qwBwfKCBntx+ZDZMYyCCd68E9VXeaIr6tLFmxB0BZpumpN5a8emRdr9bMhbU+/KDs7jKkh6R7nXHlFxiTvovxR7r3DnaZYeYP6oN+J7upYOmXcze049UmJCZrRUrcrOh0eIpxKXicKJD+m29zkpFNJDQps2CkXGB15VyKxzUSOsX3c5hB+/ipbjewJejg0H6WBTE0IsBEd5h8Q+PbrrSVlT76RQiKiAiLpTaTF826Glq16uElLI3CDU/UD/ioGExVQFv4TiosLanYGskbyv83MX8AVAj9MsBBP516HLTBVjqE+ASvhkYN3Bnzukd/kBSUCqhwd+y31TDdzGsxBiRCl5dNEtcwzsf8gMOyHcMK/6b6W7iz28AaeInXBYKY9ANkxQ89i1PTdZ50VUjVkdQzU4Swskko00oD9KSVbdLv9MrtyfDGvrT/MBHbSvMlJq66XqLCqe+yXWu9btalLYNS+4A3ETYKJkozpx/U17ygQpDD1Nj27juPEWEa1Kgt9l0GtLFgyAFUN8t8DYd8YCTIeZ2/9dMGL6GgNQN+yxO0MkIzREpCjWMiNy+3HH78=
  # bintray api key
  - secure: Yj0pWIl9W4qPz2FT9zJb2Hn0Hi5KK+KxljHJLjhxHyCrjpSgnLJy7jWXQnl2Z8b7ED0bUtDZtE8IbO/fQ5P/NrGKpc0crL/ISaiWcX+cjbCkZsaK1QjhprORvV0fkfLY8Nj+S3Z8O5xb6QGYmwo+1LdDhimPM1VEcfLMebmjrnA5/EkD8+Zt5R979FBQdTYBiLa4o8OjK4Ilsgx/zQsSaT7v6+VfFEFBzTVpk+640zed+png8my8fApu5fUxHR0rWjzgTJxTzJv07zCoUlTa3qmym/mwkZQe9QLGAmZgAdc9dXOEcYSDUzR/mGCvwLtuEx9MpPWH7ajt8hOpGv4ZT7d8WByNrMfr3vwpYAvXewp/PShBtrfWWBQHT4ETMILOVq6imoFEG3ZUOSkkD3CpBPg9o+rWXs8JIzNYFiNmEDrc9RV4Zi0epzKKMeL4QyvtT2BOQqscOWlxOBa+hoH3Pz/tddkaUSy6JwXqAJtg6W5vidK/bHOcGikL6uWgp9Oze7oDkmWgZ8ibNu1ZGePMw0FPf9vPhsyJO5hC0OZr4WXsPcwv4kiGHEPnvWOdcAuNylwYv99uhWH7Lx9yZFfF1LHZhRNDKyxPZ6r+G1CwaNsmECw/4U0ivzadoe+sNafvMKPCFCwDJOs21GO0YPSGfhJ1V8vP3iD7DVAMupVZ66M=
  # bintray gpg key
  - secure: VbdzebSSUbc49vCHRrEgDYU8GIY2YlCQx4Anf28plUEk9ROhaN/RgvVkS03p54Hz2tLdWQjzcIgtRx5qMrAZWIZ6ASwTJYmWwpNmt8SaZaQ6AMsKidNSyg3r15XRjOekQrfusSQZnZV+6JHeWcqDwRneAG9LgsL6hvbIBpnCU5O4H9k7lswdJtZMQ7V74xz4IaJbVfN+rQ73e4295h9MugzDK6MIyPao6LXW29hYHxaPAzPFQoDfdF4O+vc2MoqVqpc0paq6WNzDGVo8isFW+qngFp7hm9m/i+Upwn3iM8PnbRxCDW2ovoI9d5f0JHEfKhaiuk/K9JzAiMrpAxRculIwdw/7QsXA6tchwflXguUaIXa9aoYGYdDxpY6fGeTqePyjQP9vbK4/fBb2EM3Qh7dXuElpxq95VNxAYpCOEJ2I4PhC5Za4lcqcRSLJ5l9fe3NPYB+v+Lg98LKtUDmtmUort6vMedsYpoeiI1rdMfAEcpAiRhbnGdQdTW2dPlxtQlMnLxqAR1+u52m5tYj7kvJKRO5e9TvKKP7XdMP3Wqi1gvM14nInrvwyIEIJAx0yzRiA6yh6StQtIZ1ATof2vg0vLBEfFGENMXI5dDGPWK+lP0CBZrnU6Fxo1BXXgslm7K2puHeaDuVKdvEm8BPViuC+gkZp/GXgI1il6An7dpM=

install:
- pip install --user sphinx

script:
- cd docs
- make html
- cd ..

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    # - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    # - addon-google_apis-google-23

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17

after_success:
  - ./gradlew :sdk:cobertura :sdk:coveralls
  - CURRENT_HASH=`git rev-parse HEAD`
  - RELEASE_VERSION=`git tag | xargs -I@ git log --format=format:"%ai @%n" -1 @ | sort | awk '{print $4}' | tail -n 1`
  - RELEASE_HASH=`git rev-list $RELEASE_VERSION -n 1`
  - if [ "$CURRENT_HASH" = "$RELEASE_HASH" ]; then DEPLOY_DOCS=true; fi
  - echo $RELEASE_VERSION
  - echo $CURRENT_HASH
  - echo $RELEASE_HASH
  - echo $DEPLOY_DOCS
  - test -z "$DEPLOY_DOCS" || git config --global user.email "evangelists@stormpath.com"
  - test -z "$DEPLOY_DOCS" || git config --global user.name "stormpath-sdk-android Auto Doc Build"
  - test -z "$DEPLOY_DOCS" || git clone git@github.com:stormpath/stormpath.github.io.git
  - test -z "$DEPLOY_DOCS" || cd stormpath.github.io
  - test -z "$DEPLOY_DOCS" || git fetch origin source:source
  - test -z "$DEPLOY_DOCS" || git checkout source
  - test -z "$DEPLOY_DOCS" || rm -rf source/android/latest
  - test -z "$DEPLOY_DOCS" || rm -rf source/android/$RELEASE_VERSION
  - test -z "$DEPLOY_DOCS" || cp -r ../docs/_build/html source/android/latest
  - test -z "$DEPLOY_DOCS" || cp -r ../docs/_build/html source/android/$RELEASE_VERSION
  - test -z "$DEPLOY_DOCS" || git add --all
  - test -z "$DEPLOY_DOCS" || git commit -m "stormpath-sdk-android release $RELEASE_VERSION"
  - test -z "$DEPLOY_DOCS" || ls -la source/android
  - test -z "$DEPLOY_DOCS" || git push origin source
  - test -z "$DEPLOY_DOCS" || gem install bundler
  - test -z "$DEPLOY_DOCS" || bundle install
  - test -z "$DEPLOY_DOCS" || rake setup_github_pages[git@github.com:stormpath/stormpath.github.io.git]
  - test -z "$DEPLOY_DOCS" || cd _deploy
  - test -z "$DEPLOY_DOCS" || git pull --no-edit -s recursive -X theirs https://github.com/stormpath/stormpath.github.io.git
  - test -z "$DEPLOY_DOCS" || cd ..
  - test -z "$DEPLOY_DOCS" || rake generate
  - test -z "$DEPLOY_DOCS" || cd _deploy
  - test -z "$DEPLOY_DOCS" || git pull --no-edit -s recursive -X theirs https://github.com/stormpath/stormpath.github.io.git
  - test -z "$DEPLOY_DOCS" || cd ..
  - test -z "$DEPLOY_DOCS" || rake deploy
  - test -z "$DEPLOY_DOCS" || cd ..

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - openssl aes-256-cbc -K $encrypted_568555ef9f79_key -iv $encrypted_568555ef9f79_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

deploy:
  provider: script
  script: sh $TRAVIS_BUILD_DIR/deploy.sh
  skip_cleanup: true
  on:
    tags: true
